% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Sep-2026 15:15:56
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
                                   
sample_time_MIL = 1e-07;
F = Simulink.Parameter;
F.Value = 0.0048;
F.Complexity = 'real';
F.CoderInfo.StorageClass = 'ExportedGlobal';
F.CoderInfo.Identifier = '';
F.CoderInfo.Alignment = -1;
F.Description = ['This variable is responsible for load torque feedback' ...
                 ' based on rotor speed in the mechanical plant model.'];
F.DataType = 'single';
F.Min = [];
F.Max = [];
F.DocUnits = 'Nm/rad/s';

I_s_max = Simulink.Parameter;
I_s_max.Value = 350;
I_s_max.Complexity = 'real';
I_s_max.CoderInfo.StorageClass = 'ExportedGlobal';
I_s_max.CoderInfo.Identifier = '';
I_s_max.CoderInfo.Alignment = -1;
I_s_max.Description = 'Maximum stator current value in [A] dimension.';
I_s_max.DataType = 'single';
I_s_max.Min = [];
I_s_max.Max = [];
I_s_max.DocUnits = 'A';

J = Simulink.Parameter;
J.Value = 0.01;
J.Complexity = 'real';
J.CoderInfo.StorageClass = 'ExportedGlobal';
J.CoderInfo.Identifier = '';
J.CoderInfo.Alignment = -1;
J.Description = ['Inertia of the PMSM machine in [kg*m^2] dimension.', newline, '' ...
                 'Typical rotor inertia in high-powered PMSM machines u' ...
                 'sed in electric cars.'];
J.DataType = 'single';
J.Min = [];
J.Max = [];
J.DocUnits = 'kg*m^2';

KI_c = Simulink.Parameter;
KI_c.Value = 30;
KI_c.Complexity = 'real';
KI_c.CoderInfo.StorageClass = 'ExportedGlobal';
KI_c.CoderInfo.Identifier = '';
KI_c.CoderInfo.Alignment = -1;
KI_c.Description = 'Integral gain of the current controller.';
KI_c.DataType = 'single';
KI_c.Min = [];
KI_c.Max = [];
KI_c.DocUnits = '';

KI_w = Simulink.Parameter;
KI_w.Value = 0.072000000000000008;
KI_w.Complexity = 'real';
KI_w.CoderInfo.StorageClass = 'ExportedGlobal';
KI_w.CoderInfo.Identifier = '';
KI_w.CoderInfo.Alignment = -1;
KI_w.Description = 'Integral gain of the speed controller.';
KI_w.DataType = 'single';
KI_w.Min = [];
KI_w.Max = [];
KI_w.DocUnits = '';

Kp_c = Simulink.Parameter;
Kp_c.Value = 1.1;
Kp_c.Complexity = 'real';
Kp_c.CoderInfo.StorageClass = 'ExportedGlobal';
Kp_c.CoderInfo.Identifier = '';
Kp_c.CoderInfo.Alignment = -1;
Kp_c.Description = 'Proportional gain of the current controller.';
Kp_c.DataType = 'single';
Kp_c.Min = [];
Kp_c.Max = [];
Kp_c.DocUnits = '';

Kp_w = Simulink.Parameter;
Kp_w.Value = 0.012;
Kp_w.Complexity = 'real';
Kp_w.CoderInfo.StorageClass = 'ExportedGlobal';
Kp_w.CoderInfo.Identifier = '';
Kp_w.CoderInfo.Alignment = -1;
Kp_w.Description = 'Proportional gain of the speed controller.';
Kp_w.DataType = 'single';
Kp_w.Min = [];
Kp_w.Max = [];
Kp_w.DocUnits = '';

L_d = Simulink.Parameter;
L_d.Value = 0.0003;
L_d.Complexity = 'real';
L_d.CoderInfo.StorageClass = 'ExportedGlobal';
L_d.CoderInfo.Identifier = '';
L_d.CoderInfo.Alignment = -1;
L_d.Description = ['Direct inductance of the PMSM machine in [H] dimens' ...
                   'ion.', newline, 'In theory, a typical PMSM motor us' ...
                   'ed in 400V electric cars has ~0.3mH inductance valu' ...
                   'e.'];
L_d.DataType = 'single';
L_d.Min = [];
L_d.Max = [];
L_d.DocUnits = 'H';

L_q = Simulink.Parameter;
L_q.Value = 0.0003;
L_q.Complexity = 'real';
L_q.CoderInfo.StorageClass = 'ExportedGlobal';
L_q.CoderInfo.Identifier = '';
L_q.CoderInfo.Alignment = -1;
L_q.Description = ['Quadrature inductance of the PMSM machine in [H] di' ...
                   'mension.', newline, 'In theory, a typical PMSM moto' ...
                   'r used in 400V electric cars has ~0.3mH inductance ' ...
                   'value.'];
L_q.DataType = 'single';
L_q.Min = [];
L_q.Max = [];
L_q.DocUnits = 'H';

Psi_p = Simulink.Parameter;
Psi_p.Value = 0.095;
Psi_p.Complexity = 'real';
Psi_p.CoderInfo.StorageClass = 'Auto';
Psi_p.Description = ['Pole flux value of the PMSM machine in [Wb] dimen' ...
                     'sion.', newline, 'In theory, a typical PMSM motor' ...
                     ' used in 400V electric cars has ~0.1Wb pole-flux ' ...
                     'value.'];
Psi_p.DataType = 'single';
Psi_p.Min = [];
Psi_p.Max = [];
Psi_p.DocUnits = 'Wb';

R = Simulink.Parameter;
R.Value = 0.01;
R.Complexity = 'real';
R.CoderInfo.StorageClass = 'ExportedGlobal';
R.CoderInfo.Identifier = '';
R.CoderInfo.Alignment = -1;
R.Description = 'Stator resistance in [Ohm] dimension.';
R.DataType = 'single';
R.Min = [];
R.Max = [];
R.DocUnits = 'Ω';

T_limit_Nm = Simulink.Parameter;
T_limit_Nm.Value = 150;
T_limit_Nm.Complexity = 'real';
T_limit_Nm.CoderInfo.StorageClass = 'ExportedGlobal';
T_limit_Nm.CoderInfo.Identifier = '';
T_limit_Nm.CoderInfo.Alignment = -1;
T_limit_Nm.Description = ['Torque limit output of the speed controller ' ...
                          'in [Nm] dimension.'];
T_limit_Nm.DataType = 'single';
T_limit_Nm.Min = [];
T_limit_Nm.Max = [];
T_limit_Nm.DocUnits = 'Nm';

U_bat = Simulink.Parameter;
U_bat.Value = 400;
U_bat.Complexity = 'real';
U_bat.CoderInfo.StorageClass = 'ExportedGlobal';
U_bat.CoderInfo.Identifier = '';
U_bat.CoderInfo.Alignment = -1;
U_bat.Description = ['The nominal battery voltage used in electric cars' ...
                     '. (Tesla Model 3)'];
U_bat.DataType = 'single';
U_bat.Min = [];
U_bat.Max = [];
U_bat.DocUnits = '';

dq_decouping_ena = Simulink.Parameter;
dq_decouping_ena.Value = 1;
dq_decouping_ena.Complexity = 'real';
dq_decouping_ena.CoderInfo.StorageClass = 'ExportedGlobal';
dq_decouping_ena.CoderInfo.Identifier = '';
dq_decouping_ena.CoderInfo.Alignment = -1;
dq_decouping_ena.Description = ['This variable enables or disables the ' ...
                                'voltage decoupling logic in the FOC al' ...
                                'gorithm. Voltage decoupling boosts the' ...
                                ' performance of the current controller' ...
                                ' by feedforward technique. However, in' ...
                                ' some cases it could force the current' ...
                                ' controller to be unstable. During the' ...
                                ' wake-up of the MIL simulation, it is ' ...
                                'wise to disable it.'];
dq_decouping_ena.DataType = 'boolean';
dq_decouping_ena.Min = [];
dq_decouping_ena.Max = [];
dq_decouping_ena.DocUnits = '';

dq_voltage_ratio = Simulink.Parameter;
dq_voltage_ratio.Value = 0.57735026918962584;
dq_voltage_ratio.Complexity = 'real';
dq_voltage_ratio.CoderInfo.StorageClass = 'ExportedGlobal';
dq_voltage_ratio.CoderInfo.Identifier = '';
dq_voltage_ratio.CoderInfo.Alignment = -1;
dq_voltage_ratio.Description = ['This variable gives the maximum synthe' ...
                                'sizable voltage or even current value ' ...
                                'in unary system. The maximum synthesiz' ...
                                'able dq voltage is 1/sqrt(3) of the me' ...
                                'asured battery voltage.'];
dq_voltage_ratio.DataType = 'single';
dq_voltage_ratio.Min = [];
dq_voltage_ratio.Max = [];
dq_voltage_ratio.DocUnits = '';

duty_sat_lower = Simulink.Parameter;
duty_sat_lower.Value = 0;
duty_sat_lower.Complexity = 'real';
duty_sat_lower.CoderInfo.StorageClass = 'ExportedGlobal';
duty_sat_lower.CoderInfo.Identifier = '';
duty_sat_lower.CoderInfo.Alignment = -1;
duty_sat_lower.Description = ['This variable is needed for limiting the' ...
                              ' maximum duty output in [%] dimension to' ...
                              'wards the plant model.', newline, 'In pr' ...
                              'actice, MOSFETs and IGBTs have finite tu' ...
                              'rn on-off time values, hence 0% and 100%' ...
                              ' duty can not be realised.'];
duty_sat_lower.DataType = 'single';
duty_sat_lower.Min = [];
duty_sat_lower.Max = [];
duty_sat_lower.DocUnits = '%';

duty_sat_upper = Simulink.Parameter;
duty_sat_upper.Value = 100;
duty_sat_upper.Complexity = 'real';
duty_sat_upper.CoderInfo.StorageClass = 'ExportedGlobal';
duty_sat_upper.CoderInfo.Identifier = '';
duty_sat_upper.CoderInfo.Alignment = -1;
duty_sat_upper.Description = ['This variable is needed for limiting the' ...
                              ' maximum duty output in [%] dimension to' ...
                              'wards the plant model.', newline, 'In pr' ...
                              'actice, MOSFETs and IGBTs have finite tu' ...
                              'rn on-off time values, hence 0% and 100%' ...
                              ' duty can not be realised.'];
duty_sat_upper.DataType = 'single';
duty_sat_upper.Min = [];
duty_sat_upper.Max = [];
duty_sat_upper.DocUnits = '%';

inverter_ena = Simulink.Parameter;
inverter_ena.Value = 1;
inverter_ena.Complexity = 'real';
inverter_ena.CoderInfo.StorageClass = 'ExportedGlobal';
inverter_ena.CoderInfo.Identifier = '';
inverter_ena.CoderInfo.Alignment = -1;
inverter_ena.Description = ['This variable enables or disables the inve' ...
                            'rter.'];
inverter_ena.DataType = 'boolean';
inverter_ena.Min = [];
inverter_ena.Max = [];
inverter_ena.DocUnits = '';

p = Simulink.Parameter;
p.Value = 3;
p.Complexity = 'real';
p.CoderInfo.StorageClass = 'ExportedGlobal';
p.CoderInfo.Identifier = '';
p.CoderInfo.Alignment = -1;
p.Description = 'Number of pole-pairs of the PMSM machine.';
p.DataType = 'single';
p.Min = [];
p.Max = [];
p.DocUnits = '';

rad_s_to_rpm = Simulink.Parameter;
rad_s_to_rpm.Value = 9.5492965855137211;
rad_s_to_rpm.Complexity = 'real';
rad_s_to_rpm.CoderInfo.StorageClass = 'ExportedGlobal';
rad_s_to_rpm.CoderInfo.Identifier = '';
rad_s_to_rpm.CoderInfo.Alignment = -1;
rad_s_to_rpm.Description = ['Dimension change from [rad/s] to [RPM]. (6' ...
                            '0/(2*pi))'];
rad_s_to_rpm.DataType = 'single';
rad_s_to_rpm.Min = [];
rad_s_to_rpm.Max = [];
rad_s_to_rpm.DocUnits = '';

sample_time_MIL = Simulink.Parameter;
sample_time_MIL.Value = 1E-7;
sample_time_MIL.Complexity = 'real';
sample_time_MIL.CoderInfo.StorageClass = 'Auto';
sample_time_MIL.Description = ['Sampling time of the Model In Loop envi' ...
                               'ronment, as well as the Plant model''s.' ...
                               ''];
sample_time_MIL.DataType = 'double';
sample_time_MIL.Min = [];
sample_time_MIL.Max = [];
sample_time_MIL.DocUnits = 's';

svpwm_ena = Simulink.Parameter;
svpwm_ena.Value = 1;
svpwm_ena.Complexity = 'real';
svpwm_ena.CoderInfo.StorageClass = 'ExportedGlobal';
svpwm_ena.CoderInfo.Identifier = '';
svpwm_ena.CoderInfo.Alignment = -1;
svpwm_ena.Description = ['This variable enables or disables the svpwm a' ...
                         'lgorithm.'];
svpwm_ena.DataType = 'boolean';
svpwm_ena.Min = [];
svpwm_ena.Max = [];
svpwm_ena.DocUnits = '';

task_time_comp = Simulink.Parameter;
task_time_comp.Value = 0;
task_time_comp.Complexity = 'real';
task_time_comp.CoderInfo.StorageClass = 'ExportedGlobal';
task_time_comp.CoderInfo.Identifier = '';
task_time_comp.CoderInfo.Alignment = -1;
task_time_comp.Description = ['Task time compensation parameter for inv' ...
                              'erse Park-transformation.', newline, 'ta' ...
                              'sk_time_comp = 3/2 * task_time_mtrcntrl', newline, '' ...
                              'Compensation is needed for estimating th' ...
                              'e rotor position difference between the ' ...
                              'input interface read abd output interfac' ...
                              'e write time window.'];
task_time_comp.DataType = 'single';
task_time_comp.Min = [];
task_time_comp.Max = [];
task_time_comp.DocUnits = '';

task_time_mtrctrl = Simulink.Parameter;
task_time_mtrctrl.Value = 0.0001;
task_time_mtrctrl.Complexity = 'real';
task_time_mtrctrl.CoderInfo.StorageClass = 'Auto';
task_time_mtrctrl.Description = ['This variable defines the task time o' ...
                                 'f the field oriented control algorith' ...
                                 'm. Usually, it is 100us in most cases' ...
                                 ', however the smaller the task time, ' ...
                                 'the better the control algorithm. Mos' ...
                                 't hardwares (microcontroller CPUs) ca' ...
                                 'n handle 100us.'];
task_time_mtrctrl.DataType = 'double';
task_time_mtrctrl.Min = [];
task_time_mtrctrl.Max = [];
task_time_mtrctrl.DocUnits = 's';

w_cntrl_reset = Simulink.Parameter;
w_cntrl_reset.Value = 0;
w_cntrl_reset.Complexity = 'real';
w_cntrl_reset.CoderInfo.StorageClass = 'ExportedGlobal';
w_cntrl_reset.CoderInfo.Identifier = '';
w_cntrl_reset.CoderInfo.Alignment = -1;
w_cntrl_reset.Description = ['Variable used for reseting the integrator' ...
                             ' of the speed controller.'];
w_cntrl_reset.DataType = 'boolean';
w_cntrl_reset.Min = [];
w_cntrl_reset.Max = [];
w_cntrl_reset.DocUnits = '';

w_m_max = Simulink.Parameter;
w_m_max.Value = 10000;
w_m_max.Complexity = 'real';
w_m_max.CoderInfo.StorageClass = 'ExportedGlobal';
w_m_max.CoderInfo.Identifier = '';
w_m_max.CoderInfo.Alignment = -1;
w_m_max.Description = ['Maximum rotational speed of the motor in [RPM] ' ...
                       'dimension.'];
w_m_max.DataType = 'single';
w_m_max.Min = [];
w_m_max.Max = [];
w_m_max.DocUnits = 'RPM';

